services:
  web:
    container_name: welcome
    image: nixoletas/welcome:latest
    ports:
      - "80:80"
    restart: unless-stopped
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
